# -*- coding: utf-8 -*-
"""Lab_6vr3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VOJEmwhV0HkHDLHRA1kXTTqeT4e0_0Jf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



import csv
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

dataset=[]
with open('/content/amazon_laptop_prices_v01.csv') as file:
      reader=csv.reader(file,delimiter=',')
      for row in reader:
         dataset+=[row]

dataset[0:10]

len(dataset)

te=TransactionEncoder()
x=te.fit_transform(dataset)

x

te.columns_

df=pd.DataFrame(x, columns=te.columns_)

len(te.columns_)

df.head()

df.info()

df.columns

df.head(10)

#1. Find frequent itemsets
freq_itemset = apriori(df, min_support=0.01,use_colnames=True)

freq_itemset

#find the rules
rules=association_rules(freq_itemset, metric='confidence', min_threshold=0.25)

rules

rules=rules[['antecedents','consequents','support','confidence']]

rules

rules.head()

rules[rules['antecedents'] == {'HP'}]

